---
title: "HW1"
author: "Corinna Hong"
date: "January 13, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
```

```{r, load packages}

library(tidyverse)
library(janitor)

```

```{r, read in and wrangle adult data}

adult_organisms <- read_csv("mean_density_adult_organisms.csv")

adult_organisms_tidy <- adult_organisms %>% 
  gather(`2009`, `2018`, key = "year", value = "mean_density_per_100m2") %>% 
  arrange(organism, year) %>% 
  select(organism, lagoon, year, mean_density_per_100m2, ci95) # rearranges columns

```

#1. Mean Density of Adults
</br>
```{r, adult fish graph}

adult_fish <- adult_organisms_tidy %>% 
  filter(grepl('fish', organism)) # find anything with "fish" in organism column and keep it

labels <- c('Coral Trout (fish, predators of adult fishes)' = "Coral Trout", 
            'Spotted Damselfish (fish, eats zooplankton)' = "Spotted Damselfish",
            'Surgeonfish (fish, herbivores)' = "Surgeonfish",
            'Yellow Damselfish (fish, eats zooplankton)' = "Yellow Damselfish") # Rename organisms for facet labels

adult_fish_bar <- ggplot(adult_fish, aes(fill = year, x = lagoon, y = mean_density_per_100m2)) +
  geom_bar(position = "dodge", stat = "identity") + 
  geom_errorbar(aes(ymin = mean_density_per_100m2 + ci95, 
                    ymax = mean_density_per_100m2 - ci95), 
                width = 0.3, position =  position_dodge(.9)) +  
  labs(x = "Lagoon", y = expression(Mean~Density~(number/"100m^2")), title = "Adult Fish Comparisons") +
  facet_wrap(~ organism, labeller = labeller(organism = labels), scale = "free") + # facet wrap with new labels
  scale_y_continuous(expand = c(0,0)) +  
  theme_minimal() # or maybe go with classic?

adult_fish_bar # FINALIZE (fix the 100 m^2 problem)

```


```{r, other organisms graph}

adult_other <- adult_organisms_tidy %>% 
  filter(!(grepl('fish', organism))) # remonve anything with "fish" from organism column


adult_other_bar <- ggplot(adult_other, aes(fill = year, x = lagoon, y = mean_density_per_100m2)) +
  geom_bar(position = "dodge", stat = "identity") + 
  geom_errorbar(aes(ymin = mean_density_per_100m2 + ci95, 
                    ymax = mean_density_per_100m2 - ci95),
                width = 0.3, position=position_dodge(.9)) +  
  labs(x = "Lagoon", y = expression(Mean~Density~(m^2/"100m^2")), title = "Adult Organisms Comparisons") +
  facet_wrap(~ organism, scale = "free") + # facet wrap with new labels  
  scale_y_continuous(expand = c(0,0)) +
  theme_minimal() # or maybe go with classic?

adult_other_bar # FINALIZE (fix the 100m^2 problem, resize/rearragne facet graphs)

```

#2. Mean Density of Recruit Organisms
</br>
```{r, read in and wrangle recruit data}

recruit_organisms <- read_csv("mean_number_new_recruits.csv")

recruit_organisms_tidy <- recruit_organisms %>%
  gather(`Rarotonga_2009`, `Aitutaki_2009`, `Rarotonga_2018`, `Aitutaki_2018`, key = "lagoon", value = "density") %>%
  clean_names() %>% 
  separate(lagoon, into = c ("lagoon","year"), sep = "_") %>% 
  arrange(fish) %>% 
  select (fish, microhabitat, lagoon, year, density, ci)

```

```{r, recruit graph}

recruit_organisms_bar <- ggplot(recruit_organisms_tidy, aes(fill = year, x = lagoon, y = density)) +
  geom_bar(position = "dodge", stat = "identity") +
  geom_errorbar(aes(ymin = density + ci, 
                    ymax = density - ci),
                width = 0.3, position=position_dodge(.9)) +  
  labs(x = "Lagoon", y = expression(Mean~Density~(number/m^2)), title = "Fish Recruit Comparisons") +
  facet_wrap(~ fish, scale = "free") +  
  scale_y_continuous(expand = c(0,0)) +
  theme_minimal() # or maybe go with classic?

recruit_organisms_bar # FINALIZE, remove black line at the bottom.

```

#3. Density of recruits and adults per area of reef
</br>
```{r, read in and wrangle adult and recruit data}

adult_recruit <- read_csv("adult_recruit_density.csv")

adult_recruit_tidy <- adult_recruit %>%
  gather(`Rarotonga_2009`, `Aitutaki_2009`, `Rarotonga_2018`, `Aitutaki_2018`, key = "lagoon", value = "density") %>%
  separate(lagoon, into = c ("lagoon","year"), sep = "_") %>%
  spread(Type, density) %>%
  clean_names() %>%
  arrange(fish)

```

```{r, calculate r-squared values}



```


```{r, adults and recruits graphs}

adult_recruit_scatter <- ggplot(adult_recruit_tidy, aes(x = recruit, y = adult)) +
  geom_point(aes(color = lagoon,
                 shape = year)) +
  geom_smooth(method = "lm", se = FALSE, color = "grey50", size = 0.5) +
  facet_wrap( ~ fish, scale = "free") +
  labs(x = "Recruit Density (number/100m^2)", y = "Adult Density (number/100m^2)", title = "Recruit and Adult Density") +
  theme_minimal()

adult_recruit_scatter #FINALIZE, add R2 values, also recuits v. adults or adults v. recruits?

```

#4. Adults and microhabitat
</br>

```{r, read in and wrangle adult and microhabitat data}

adult_micro <- read_csv("adult_microhabitat.csv")

adult_micro_tidy <- adult_micro %>% 
  gather(`Rarotonga_2009`, `Aitutaki_2009`, `Rarotonga_2018`, `Aitutaki_2018`, key = "lagoon", value = "density") %>%
  separate(lagoon, into = c ("lagoon","year"), sep = "_") %>% 
  spread(Type, density) %>% 
  clean_names()

```

```{r, r-squared}



```

```{r, adult microhabitat graph}

adult_micro_scatter <- ggplot(adult_micro_tidy, aes(x = microhabitat, y = adult)) +
  geom_point(aes(color = lagoon,
                 shape = year)) +
  geom_smooth(method = "lm", se = FALSE, color = "grey50", size = 0.5) +
  facet_wrap( ~ fish, scale = "free") +
  labs(x = "Recruit Microhabitat Density (m^2/100m^2)", y = "Adult Density (number/100m^2)", title = "Adult and microhabitat density") +
  theme_minimal()

adult_micro_scatter

```

#5. Density of Adults per Area of Bottom Cover

```{r}



```

#6. Pair Comparisons

```{r, read in and wrangle data}

adult_compare <- read_csv("adult_compare.csv")

adult_compare_tidy <- adult_compare %>% 
  gather(`Rarotonga_2009`, `Aitutaki_2009`, `Rarotonga_2018`, `Aitutaki_2018`, key = "lagoon", value = "density") %>% 
  separate(lagoon, into = c ("lagoon","year"), sep = "_") %>% 
  spread(Fish, density) %>% 
  clean_names()

```


```{r, make graph}

adult_pair_scatter <- ggplot(adult_compare_tidy, aes(x = surgeonfish, y = coral_trout)) +
  geom_point(aes(color = lagoon,
                 shape = year)) +
  geom_smooth(method = "lm", se = FALSE, color = "grey50", size = 0.5) +
  labs(x = "Surgeonfish", y = "Coral Trout", title = "Coral Trout v. Surgeonfish") +
  theme_minimal()

adult_pair_scatter # Finalize, change size

```

```{r}

adult_pair_scatter2 <- ggplot(adult_compare_tidy, aes(x = surgeonfish, y = spotted_damselfish)) +
  geom_point(aes(color = lagoon,
                 shape = year)) +
  geom_smooth(method = "lm", se = FALSE, color = "grey50", size = 0.5) +
  labs(x = "Surgeonfish", y = "Spotted Damselfish", title = "Spotted Damselfish v. Surgeonfish") +
  theme_minimal()

adult_pair_scatter2 # Finalize, change size

```

```{r}

adult_pair_scatter3 <- ggplot(adult_compare_tidy, aes(x = surgeonfish, y = yellow_damselfish)) +
  geom_point(aes(color = lagoon,
                 shape = year)) +
  geom_smooth(method = "lm", se = FALSE, color = "grey50", size = 0.5) +
  labs(x = "Surgeonfish", y = "Yellwo Damselfish", title = "Yellow Damselfish v. Surgeonfish") +
  theme_minimal()

adult_pair_scatter3 # Finalize, change size

```

```{r}

adult_pair_scatter4 <- ggplot(adult_compare_tidy, aes(x = coral_trout, y = spotted_damselfish)) +
  geom_point(aes(color = lagoon,
                 shape = year)) +
  geom_smooth(method = "lm", se = FALSE, color = "grey50", size = 0.5) +
  labs(x = "Coral Trout", y = "Spotted Damselfish", title = "Spotted Damselfish v. Coral Trout") +
  theme_minimal()

adult_pair_scatter4 # Finalize, change size

```

```{r}

adult_pair_scatter5 <- ggplot(adult_compare_tidy, aes(x = coral_trout, y = yellow_damselfish)) +
  geom_point(aes(color = lagoon,
                 shape = year)) +
  geom_smooth(method = "lm", se = FALSE, color = "grey50", size = 0.5) +
  labs(x = "Coral Trout", y = "Yellow Damselfish", title = "Yellow Damselfish v. Coral Trout") +
  theme_minimal()

adult_pair_scatter5 # Finalize, change size

```

```{r}

adult_pair_scatter6 <- ggplot(adult_compare_tidy, aes(x = yellow_damselfish, y = spotted_damselfish)) +
  geom_point(aes(color = lagoon,
                 shape = year)) +
  geom_smooth(method = "lm", se = FALSE, color = "grey50", size = 0.5) +
  labs(x = "Yellow Damselfish", y = "Spotted Damselfish", title = "Spotted Damselfish v. Yellow Damselfish") +
  theme_minimal()

adult_pair_scatter6 # Finalize, change size  
  
```

